export default function colour (name) {
  const gen = code => '\x1B[' + code + 'm'

  const colours = {
    reset: 0,
    bold: 1,
    dim: 2,
    underlined: 4,
    blink: 5,
    invert: 7,
    hidden: 8,
    bold_r: 21,
    dim_r: 22,
    underlined_r: 24,
    blink_r: 25,
    invert_r: 27,
    hidden_r: 28,
    f_default: 39,
    f_black: 30,
    f_red: 31,
    f_green: 32,
    f_yellow: 33,
    f_blue: 34,
    f_magenta: 35,
    f_cyan: 36,
    f_lightgray: 37,
    f_darkgray: 90,
    f_lightred: 91,
    f_lightgreen: 92,
    f_lightyellow: 93,
    f_lightblue: 94,
    f_lightmagenta: 95,
    f_lightcyan: 96,
    f_white: 97,
    b_default: 49,
    b_black: 40,
    b_red: 41,
    b_green: 42,
    b_yellow: 43,
    b_blue: 44,
    b_magenta: 45,
    b_cyan: 46,
    b_lightgray: 47,
    b_darkgray: 100,
    b_lightred: 101,
    b_lightgreen: 102,
    b_lightyellow: 103,
    b_lightblue: 104,
    b_lightmagenta: 105,
    b_lightcyan: 106,
    b_white: 107
  }

  return gen(colours[name])
}
